//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Auto.Common.Entitis
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum nav_agreementState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("nav_agreement")]
	public partial class nav_agreement : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string nav_agreementId = "nav_agreementid";
			public const string Id = "nav_agreementid";
			public const string nav_autoid = "nav_autoid";
			public const string nav_contact = "nav_contact";
			public const string nav_creditamount = "nav_creditamount";
			public const string nav_creditamount_Base = "nav_creditamount_base";
			public const string nav_creditid = "nav_creditid";
			public const string nav_creditperiod = "nav_creditperiod";
			public const string nav_date = "nav_date";
			public const string nav_fact = "nav_fact";
			public const string nav_factsumma = "nav_factsumma";
			public const string nav_factsumma_Base = "nav_factsumma_base";
			public const string nav_fullcreditamount = "nav_fullcreditamount";
			public const string nav_fullcreditamount_Base = "nav_fullcreditamount_base";
			public const string nav_initialfee = "nav_initialfee";
			public const string nav_initialfee_Base = "nav_initialfee_base";
			public const string nav_name = "nav_name";
			public const string nav_paymentplandate = "nav_paymentplandate";
			public const string nav_summa = "nav_summa";
			public const string nav_summa_Base = "nav_summa_base";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string nav_contact_nav_agreement_contact = "nav_contact_nav_agreement_contact";
			public const string nav_nav_auto_nav_agreement_autoid = "nav_nav_auto_nav_agreement_autoid";
			public const string nav_nav_credit_nav_agreement_creditid = "nav_nav_credit_nav_agreement_creditid";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public nav_agreement() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "nav_agreement";
		
		public const string EntitySchemaName = "nav_agreement";
		
		public const string PrimaryIdAttribute = "nav_agreementid";
		
		public const string PrimaryNameAttribute = "nav_name";
		
		public const string EntityLogicalCollectionName = "nav_agreements";
		
		public const string EntitySetName = "nav_agreements";
		
		public const int EntityTypeCode = 10410;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, создавшего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Дата и время создания записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя-представителя, создавшего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Курс валюты, связанной с сущностью, по отношению к базовой валюте.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
			set
			{
				this.OnPropertyChanging("ExchangeRate");
				this.SetAttributeValue("exchangerate", value);
				this.OnPropertyChanged("ExchangeRate");
			}
		}
		
		/// <summary>
		/// Порядковый номер импорта, в результате которого была создана эта запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, изменившего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Дата и время изменения записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя-представителя, изменившего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для экземпляров сущности.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_agreementid")]
		public System.Nullable<System.Guid> nav_agreementId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("nav_agreementid");
			}
			set
			{
				this.OnPropertyChanging("nav_agreementId");
				this.SetAttributeValue("nav_agreementid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("nav_agreementId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_agreementid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.nav_agreementId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_autoid")]
		public Microsoft.Xrm.Sdk.EntityReference nav_autoid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("nav_autoid");
			}
			set
			{
				this.OnPropertyChanging("nav_autoid");
				this.SetAttributeValue("nav_autoid", value);
				this.OnPropertyChanged("nav_autoid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_contact")]
		public Microsoft.Xrm.Sdk.EntityReference nav_contact
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("nav_contact");
			}
			set
			{
				this.OnPropertyChanging("nav_contact");
				this.SetAttributeValue("nav_contact", value);
				this.OnPropertyChanged("nav_contact");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_creditamount")]
		public Microsoft.Xrm.Sdk.Money nav_creditamount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_creditamount");
			}
			set
			{
				this.OnPropertyChanging("nav_creditamount");
				this.SetAttributeValue("nav_creditamount", value);
				this.OnPropertyChanged("nav_creditamount");
			}
		}
		
		/// <summary>
		/// Значение поля Сумма кредита в базовой валюте.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_creditamount_base")]
		public Microsoft.Xrm.Sdk.Money nav_creditamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_creditamount_base");
			}
			set
			{
				this.OnPropertyChanging("nav_creditamount_Base");
				this.SetAttributeValue("nav_creditamount_base", value);
				this.OnPropertyChanged("nav_creditamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_creditid")]
		public Microsoft.Xrm.Sdk.EntityReference nav_creditid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("nav_creditid");
			}
			set
			{
				this.OnPropertyChanging("nav_creditid");
				this.SetAttributeValue("nav_creditid", value);
				this.OnPropertyChanged("nav_creditid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_creditperiod")]
		public System.Nullable<int> nav_creditperiod
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("nav_creditperiod");
			}
			set
			{
				this.OnPropertyChanging("nav_creditperiod");
				this.SetAttributeValue("nav_creditperiod", value);
				this.OnPropertyChanged("nav_creditperiod");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_date")]
		public System.Nullable<System.DateTime> nav_date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("nav_date");
			}
			set
			{
				this.OnPropertyChanging("nav_date");
				this.SetAttributeValue("nav_date", value);
				this.OnPropertyChanged("nav_date");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_fact")]
		public System.Nullable<bool> nav_fact
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("nav_fact");
			}
			set
			{
				this.OnPropertyChanging("nav_fact");
				this.SetAttributeValue("nav_fact", value);
				this.OnPropertyChanged("nav_fact");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_factsumma")]
		public Microsoft.Xrm.Sdk.Money nav_factsumma
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_factsumma");
			}
			set
			{
				this.OnPropertyChanging("nav_factsumma");
				this.SetAttributeValue("nav_factsumma", value);
				this.OnPropertyChanged("nav_factsumma");
			}
		}
		
		/// <summary>
		/// Значение поля Оплаченная сумма в базовой валюте.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_factsumma_base")]
		public Microsoft.Xrm.Sdk.Money nav_factsumma_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_factsumma_base");
			}
			set
			{
				this.OnPropertyChanging("nav_factsumma_Base");
				this.SetAttributeValue("nav_factsumma_base", value);
				this.OnPropertyChanged("nav_factsumma_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_fullcreditamount")]
		public Microsoft.Xrm.Sdk.Money nav_fullcreditamount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_fullcreditamount");
			}
			set
			{
				this.OnPropertyChanging("nav_fullcreditamount");
				this.SetAttributeValue("nav_fullcreditamount", value);
				this.OnPropertyChanged("nav_fullcreditamount");
			}
		}
		
		/// <summary>
		/// Значение поля Полная стоимость кредита в базовой валюте.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_fullcreditamount_base")]
		public Microsoft.Xrm.Sdk.Money nav_fullcreditamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_fullcreditamount_base");
			}
			set
			{
				this.OnPropertyChanging("nav_fullcreditamount_Base");
				this.SetAttributeValue("nav_fullcreditamount_base", value);
				this.OnPropertyChanged("nav_fullcreditamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_initialfee")]
		public Microsoft.Xrm.Sdk.Money nav_initialfee
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_initialfee");
			}
			set
			{
				this.OnPropertyChanging("nav_initialfee");
				this.SetAttributeValue("nav_initialfee", value);
				this.OnPropertyChanged("nav_initialfee");
			}
		}
		
		/// <summary>
		/// Значение поля Первоначальный взнос в базовой валюте.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_initialfee_base")]
		public Microsoft.Xrm.Sdk.Money nav_initialfee_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_initialfee_base");
			}
			set
			{
				this.OnPropertyChanging("nav_initialfee_Base");
				this.SetAttributeValue("nav_initialfee_base", value);
				this.OnPropertyChanged("nav_initialfee_Base");
			}
		}
		
		/// <summary>
		/// Имя настраиваемой сущности.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_name")]
		public string nav_name
		{
			get
			{
				return this.GetAttributeValue<string>("nav_name");
			}
			set
			{
				this.OnPropertyChanging("nav_name");
				this.SetAttributeValue("nav_name", value);
				this.OnPropertyChanged("nav_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_paymentplandate")]
		public System.Nullable<System.DateTime> nav_paymentplandate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("nav_paymentplandate");
			}
			set
			{
				this.OnPropertyChanging("nav_paymentplandate");
				this.SetAttributeValue("nav_paymentplandate", value);
				this.OnPropertyChanged("nav_paymentplandate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_summa")]
		public Microsoft.Xrm.Sdk.Money nav_summa
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_summa");
			}
			set
			{
				this.OnPropertyChanging("nav_summa");
				this.SetAttributeValue("nav_summa", value);
				this.OnPropertyChanged("nav_summa");
			}
		}
		
		/// <summary>
		/// Значение поля Сумма в базовой валюте.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_summa_base")]
		public Microsoft.Xrm.Sdk.Money nav_summa_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("nav_summa_base");
			}
			set
			{
				this.OnPropertyChanging("nav_summa_Base");
				this.SetAttributeValue("nav_summa_base", value);
				this.OnPropertyChanged("nav_summa_Base");
			}
		}
		
		/// <summary>
		/// Дата и время переноса записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Идентификатор ответственного
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор бизнес-единицы, владеющей этой записью
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор рабочей группы, ответственной за запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, ответственного за запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Статус Договор
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Auto.Common.Entitis.nav_agreementState> StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Auto.Common.Entitis.nav_agreementState)(System.Enum.ToObject(typeof(Auto.Common.Entitis.nav_agreementState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Причина состояния Договор
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual nav_agreement_StatusCode? StatusCode
		{
			get
			{
				return ((nav_agreement_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Только для внутреннего использования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор валюты, связанной с сущностью.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Код часового пояса, который использовался при создании записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Номер версии
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
			set
			{
				this.OnPropertyChanging("VersionNumber");
				this.SetAttributeValue("versionnumber", value);
				this.OnPropertyChanged("VersionNumber");
			}
		}
		
		/// <summary>
		/// 1:N nav_nav_agreement_nav_invoice_dogovorid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("nav_nav_agreement_nav_invoice_dogovorid")]
		public System.Collections.Generic.IEnumerable<Auto.Common.Entitis.nav_invoice> nav_nav_agreement_nav_invoice_dogovorid
		{
			get
			{
				return this.GetRelatedEntities<Auto.Common.Entitis.nav_invoice>("nav_nav_agreement_nav_invoice_dogovorid", null);
			}
			set
			{
				this.OnPropertyChanging("nav_nav_agreement_nav_invoice_dogovorid");
				this.SetRelatedEntities<Auto.Common.Entitis.nav_invoice>("nav_nav_agreement_nav_invoice_dogovorid", null, value);
				this.OnPropertyChanged("nav_nav_agreement_nav_invoice_dogovorid");
			}
		}
		
		/// <summary>
		/// N:1 nav_contact_nav_agreement_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_contact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("nav_contact_nav_agreement_contact")]
		public Auto.Common.Entitis.Contact nav_contact_nav_agreement_contact
		{
			get
			{
				return this.GetRelatedEntity<Auto.Common.Entitis.Contact>("nav_contact_nav_agreement_contact", null);
			}
			set
			{
				this.OnPropertyChanging("nav_contact_nav_agreement_contact");
				this.SetRelatedEntity<Auto.Common.Entitis.Contact>("nav_contact_nav_agreement_contact", null, value);
				this.OnPropertyChanged("nav_contact_nav_agreement_contact");
			}
		}
		
		/// <summary>
		/// N:1 nav_nav_auto_nav_agreement_autoid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_autoid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("nav_nav_auto_nav_agreement_autoid")]
		public Auto.Common.Entitis.nav_auto nav_nav_auto_nav_agreement_autoid
		{
			get
			{
				return this.GetRelatedEntity<Auto.Common.Entitis.nav_auto>("nav_nav_auto_nav_agreement_autoid", null);
			}
			set
			{
				this.OnPropertyChanging("nav_nav_auto_nav_agreement_autoid");
				this.SetRelatedEntity<Auto.Common.Entitis.nav_auto>("nav_nav_auto_nav_agreement_autoid", null, value);
				this.OnPropertyChanged("nav_nav_auto_nav_agreement_autoid");
			}
		}
		
		/// <summary>
		/// N:1 nav_nav_credit_nav_agreement_creditid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nav_creditid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("nav_nav_credit_nav_agreement_creditid")]
		public Auto.Common.Entitis.nav_credit nav_nav_credit_nav_agreement_creditid
		{
			get
			{
				return this.GetRelatedEntity<Auto.Common.Entitis.nav_credit>("nav_nav_credit_nav_agreement_creditid", null);
			}
			set
			{
				this.OnPropertyChanging("nav_nav_credit_nav_agreement_creditid");
				this.SetRelatedEntity<Auto.Common.Entitis.nav_credit>("nav_nav_credit_nav_agreement_creditid", null, value);
				this.OnPropertyChanged("nav_nav_credit_nav_agreement_creditid");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public nav_agreement(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["nav_agreementid"] = base.Id;
                        break;
                    case "nav_agreementid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}