//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
// Created via this command line: "C:\Users\Boba761\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://orgbf2f0f19.api.crm4.dynamics.com" /namespace:"Auto.Common.Entitis" /SuppressGeneratedCodeAttribute /out:"E:\Work\Navicons\Tasks\Auto\Auto.Plugins\Entitis\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]
[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.93")]

namespace Auto.Common.Entitis
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_agreement"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_agreement> nav_agreementSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_agreement>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_auto"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_auto> nav_autoSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_auto>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_brand"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_brand> nav_brandSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_brand>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_communication"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_communication> nav_communicationSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_communication>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_credit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_credit> nav_creditSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_credit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_invoice"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_invoice> nav_invoiceSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_invoice>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_model"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_model> nav_modelSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_model>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Auto.Common.Entitis.nav_nav_auto_nav_credit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Auto.Common.Entitis.nav_nav_auto_nav_credit> nav_nav_auto_nav_creditSet
		{
			get
			{
				return this.CreateQuery<Auto.Common.Entitis.nav_nav_auto_nav_credit>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
		{
			this.Color = color;
			this.Description = description;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}